{
    "0": "Endless Desires\"The Dancer Groups Towards The Desire\"",
    "2": "Endless Desires\"The Dancer Groups Towards The Desire-CherryBlossoms-\"",
    "4": "Butterfly acceptance's Sign \"Abysmal Universe\"",
    "6": "Butterfly acceptance's Sign \"Abysmal Universe Cherry-Blossoms-\"",
    "8": "Cherry Blossom Rehash Sign \"Perfect Ink-Black Cherry Blossom-Bloom-\"",
    "12": "Cherry Blossom Sign \"Saigyou Cherry Blossom Blizzard\"",
    "14": "Echo Sign \"Echo From The 5.5th dimension\"",
    "16": "Echo Sign \"Echo From The 5.5th dimension\"",
    "18": "Echo Sign \"Echo From The 11th dimension\"",
    "22": "Mansion Echo \"Echo From The Scarlet Talker\"",
    "24": "Mansion Echo \"Echo From The Scarlet Screamer\"",
    "26": "Great Voice \"Charged Cry\"",
    "28": "Great Voice \"Charged Flaming Site of Yahoo!\"",
    "30": "Rainbow Sign \"Umbrella Cyclone\"",
    "32": "Battle Scars Sign \"Stabbed by the foe\"",
    "36": "Poison Nail \"Poison Raze\"",
    "38": "Poison Nail \"Poison Murder\"",
    "40": "Desire Sign \"Saved Up Desire Spirit Invitation\"",
    "42": "Desire Spirit \"Score Desire Eater\"",
    "44": "Evil Sign \"Yǎng Xiǎoguǐ\"",
    "45": "Evil Sign \"Gūhún Yěguǐ\"",
    "47": "Self Sacrifice \"Tatical Suicidal Zombie\"",
    "51": "Combined Soul Trade \"Red and Black Emergency\"",
    "53": "Combined Soul Trade \"Red and Black EmergencyEveryday\"",
    "55": "Taoist Sign \"Tao Fetal Movement\"",
    "59": "Clover Sign \"Unhearable Desire\"",
    "60": "Clover Sign \"Broken Down Clover's Luck\"",
    "61": "Clover Sign \"Clover Tornado\"",
    "62": "Rapids Sign \"Desire of Regen\"",
    "64": "Rapids Sign \"Desire Dream of a Secret Rapid\"",
    "66": "Fear Feat Sign \"Gils of The Pool of Endless Lies\"",
    "70": "Red Fish Out of The Pond Sign \"Suprise!!\"",
    "72": "Red Fish Out of The Pond Sign \"Suprise!! Hard or Lunatic Right\"",
    "74": "Scale of The Fishy Girl \"Funniest Joke Called Scales\"",
    "78": "True Desire \"13th Desire Unheard Desire\"",
    "80": "True Desire \"13th Honor's Towards Faith\"",
    "82": "True Hermit Sign \"13th Pray Desires of The Sun God\"",
    "84": "True Hermit Sign \"13th Prayer Desires of The Sun God\"",
    "86": "True Trance \"Fire Flare 13th Century Dream\"",
    "90": "13 Sacred Treasures \"The Treasure of Miko's Desire\"",
    "93": "13 Sacred Treasures \"The Treasure of Miko's Desires of A Secret Land\"",
    "94": "Red and White With Black and White Sign \"Amulet Stardust\"",
    "96": "Red and Black Sign \"Amulet Stardust of A Longing Desire\"",
    "98": "Protection Desire \"To Protect Our Master's\"",
    "100": "Protecton Light of Desire \"Honor of the Desire to Protect\"",
    "102": "\"Ultimate 13 Desires of Miko\"",
    "104": "\"Longing of 13 Desires of Endless Deep Dreams of Nature\"",
    "106": "Unknown \"Will-o'-wisps in Unknown Orbit\"",
    "107": "Unknown \"Skyfish with Unknown Shape\"",
    "108": "Unknown \"Youkai Orb of Unknown Mechanics\"",
    "109": "First Duel \"Tanu Tanukis Certain Dreams\"",
    "110": "Second Duel \"Otter Wolfs Beasts True Target\"",
    "111": "Third Duel \"Creepy Steps Towards a New World\"",
    "112": "Fourth Duel \"Transformation Into Happiness the Sadness\"",
    "113": "Fifth Duel \"Dance Dance Dance The Power Grows\"",
    "114": "Sixth Duel \"Tanuki's Monster's School\"",
    "115": "Seventh Duel \"Wild Deserted Island\"",
    "116": "Transformation \"So Anyways The Blasting Star of A Witch\"",
    "117": "\"Mamizou Danmaku in Ten Transformations\"",
    "118": "Ultimate Dual Transformation of A Tanu",
    "119": "Cherry Blossom Sign \"Cherry Blossom Blizzard Hell\"",
    "120": "Mountain Echo \"Yamabiko's Specialty Echo Demonstration\"",
    "121": "Poison Nail \"Undead Murderer\"",
    "122": "Taoist Sign \"TAO Fetal Movement ~Dao~\"",
    "123": "Vengeful Spirit \"Iruka's Thunder\"",
    "124": "Saint Girl \"Sun Goddess's Sacrifice\"",
    "125": "\"Divine Spirits' Universe\"",
    "126": "\"Wild Carpet\""
}