{
    "0": "Ice Sign \"Ultimate Blizzard\"",
    "2": "Water Sign \"Tail Fin Slap\"",
    "6": "Scale Sign \"Scale Wave\"",
    "8": "Scale Sign \"Raging Waves of the Reversed Scale\"",
    "9": "Scale Sign \"Great Raging Waves of the Reversed Scale\"",
    "10": "Flight Sign \"Flying Head\"",
    "14": "Neck Sign \"Close-Eye Shot\"",
    "16": "Neck Sign \"Rokurokubi Flight\"",
    "18": "Flying Head \"Multiplicative Head\"",
    "20": "Flying Head \"Seventh Head\"",
    "21": "Flying Head \"Ninth Head\"",
    "22": "Flying Head \"Dullahan Night\"",
    "26": "Fang Sign \"Moonlit Canine Teeth\"",
    "28": "Flare Force \"Flare\"",
    "30": "Flare Force Omega \"Giga Flare\"",
    "32": "Ring Of Demon's Wrath \"Murdered Hero\"",
    "34": "Snow Globe Sign \"Freezing Nightmare\"",
    "36": "Abnormal Mystic Sign \"A Drawing From The Young\"",
    "38": "Mystical Hardy Lunatic \"True Double Mystical Sqaure Revival\"",
    "40": "Heikyoku \"Sounds of Jetavana's Bell\"",
    "44": "Vengeful Spirit \"Hoichi the Earless\"",
    "46": "Vengeful Spirit \"Great Vengeful Spirit of Taira\"",
    "48": "Music Sign \"Wicked Musical Score\"",
    "50": "Music Sign \"Malicious Musical Score\"",
    "51": "Music Sign \"Double Score\"",
    "52": "Koto Sign \"Sounds of Anicca's Koto\"",
    "56": "Echo Sign \"Heian's Reverberation\"",
    "58": "Echo Sign \"Echo Chamber\"",
    "60": "Koto Music \"Social Upheaval Koto Music Complement\"",
    "62": "Koto Music \"Social Upheaval Requiem\"",
    "64": "Deceit Sign \"Reverse Needle Attack\"",
    "68": "Reverse Sign \"Danmaku Through the Looking-Glass\"",
    "70": "Reverse Sign \"Evil in the Mirror\"",
    "72": "Reverse Sign \"This Side Down\"",
    "74": "Reverse Sign \"Overturning All Under Heaven\"",
    "76": "Reverse Bow \"Dream Bow of Heaven & Earth\"",
    "78": "Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\"",
    "80": "Turnabout \"Reverse Hierarchy\"",
    "82": "Turnabout \"Change Air Brave\"",
    "84": "Bewitched Sign \"Bamboo Flames\"",
    "86": "Cursed Sign \"Bamboo Rising Flames\"",
    "88": "Heart Throbber \"Heart Growth Drunkard!\"",
    "90": "Heart Throbber \"Heart Growth ONI-GOD!\"",
    "92": "Bewitched Slashing Leaf \"Bright Winds of Faith\"",
    "96": "Mallet \"You Grow SMALLER!\"",
    "100": "\"Strong Hero's Karma\"",
    "102": "\"Wall of Karma\"",
    "104": "\"Hop-o'-My-Thumb Seven\"",
    "106": "\"The Seven Issun-Boshi\"",
    "108": "String Music \"Storm Ensemble\"",
    "109": "String Music \"Joururi World\"",
    "110": "First Drum \"Raging Temple Taiko\"",
    "111": "Second Drum \"Vengeful Spirit Aya-no-Tsuzumi\"",
    "112": "Third Drum \"Three Strikes at Midnight\"",
    "113": "Death Drum \"Land Percuss\"",
    "114": "Fifth Drum \"Den-Den Daiko\"",
    "115": "Sixth Drum \"Alternate Sticking\"",
    "116": "Seventh Drum \"High Speed Taiko Rocket\"",
    "117": "Eighth Drum \"Thunder God's Anger\"",
    "118": "\"Blue Lady Show\"",
    "119": "\"Pristine Beat\""
}