{
    "2": "Water Sign \"Drowning a Village\"",
    "3": "Frozen Sign \"Cluster Kingdom\"",
    "4": "Crashing Clouds Sign \"Rain From the Moon\"",
    "5": "Ice Queen \"SnowFlake Killer\"",
    "6": "Thrashing Rapids Sign \"Torn Earth to the Water\"",
    "7": "Scream \"Raging Screamer\"",
    "8": "Nightmare \"Crippling Spiralling Nightmare\"",
    "9": "Bloody Murder \"Crushed To Purity\"",
    "10": "Chosen Death \"Red Blood or Blue Blood\"",
    "11": "\"Trembling Shivering Purity Horizons\"",
    "12": "Slit Neck\"Cross Reailty Neck To The Other Side\"",
    "14": "Howling Sign \"Howl To The Other Side\"",
    "15": "\"20XX: Several Years of Burning Alive City\"",
    "16": "Happy Life \"Immortality's Hug Of Lovers\"",
    "17": "Beast's Fang \"Eaten Alive\"",
    "18": "Great Opening \"Creation Of Everything\"",
    "19": "\"Dancing Into the Firey Abyss\"",
    "1": "\"Resurrection\"",
    "21": "Duelist \"-Body Guard Protection- -Creation Sign True Body Guard-\"",
    "22": "Removal Sign \"Remove All Your Organs For a Feast\"",
    "23": "Collection Sign \"Collect The Heart\"",
    "24": "Storming Arts \"Simply Easy to Create\"",
    "25": "Count Down Sign \"Doom To The Soul\"",
    "26": "Hallway Arts \"Defense System of A Beautiful Hall\"",
    "28": "Seeing The Lost Music Sign \"The Spirits Of Song\"",
    "29": "Noise Sign \"Tweening Intruments\"",
    "30": "Magic Defense Sign \"7ft Under Aero-Books Combo\"",
    "31": "Strong Music \"Fire Music Beater\"",
    "32": "Double-Solo Score \"Score Web\"",
    "33": "Crushing Fear \"Planet of Emerald\"",
    "34": "Double Chant \"Song of Falling Stars\"",
    "36": "Photography \"Scraps of Pictures\"",
    "37": "Top of the River \"Fleeting Rivers\"",
    "38": "Submerged Waterfall Sign \"Shiraito Falls\"",
    "39": "War Sign \"Spear of Destiny\"",
    "40": "Heartless Angel Sign \"Unspoken Soldier\"",
    "41": "Pure Rage \"Horrific Rage of a Mother\"",
    "42": "\"Instant Shot Journalist\"",
    "43": "Streaming Love Sign \"Loving Final Master Spark\"",
    "44": "Maid of Time Sign \"Silver Binded Dead Doll\"",
    "45": "Light Sign \"7 rays of light, -Firza- -Blizzaza-\"",
    "46": "Miku Miku Sign \"Let's Go and Spin!!!\"",
    "47": "Love Sign \"Master Spark Shotgun\"",
    "48": "Time and Space Sign \"Space and Time Under My Control\"",
    "49": "Trinity KeyBlade Sign \"Infinity, Sonic Blade and Strike Raid\"",
    "50": "Giga Super Miku Sign \"Super-Duper-Mega Miku BEAM\"",
    "52": "No Right To be Here Sign \"Return Enemy to Origin\"",
    "53": "\"Fantasy Seal Rigged To Death\"",
    "54": "\"Living Organism Killing Circle\"",
    "55": "\"Divine Ying-Yang Fantasy's Orb \"",
    "56": "\"Removed From Reality!\"",
    "57": "I'm going to Seal You in This Castle",
    "58": "God's Wrath \"Unheard of Stories\"",
    "59": "Frog's Luck \"Breaking The Rainbow\"",
    "60": "Broken Rainbow \"Untouched Light\"",
    "61": "Into The Void Sign \"Void Oni\"",
    "62": "\"Goddess Biggest Stream of Nukes\"",
    "63": "Frog Sign \"Bloody Mound of Rainbow Frogs in Rings\"",
    "64": "StarGaze \"Watch the Stars ~Lessa Devita Flower~\"",
    "65": "Social Anxiety of Android \"Too Many Oni\"",
    "66": "\"I Cannot Go on, My mind Hurts\"",
    "67": "\"Heaven or Hell is Going to Break Me\"",
    "68": "\"My Skin is Fake\"",
    "69": "\"Less than the Fingers on My Hand\"",
    "70": "\"Trapped In a Danmaku Hell\"",
    "71": "\"I NEED a Miracle or Something\"",
    "72": "\"I'm Neither God, Human or Yokai?\"",
    "73": "\"Mind Thobbing Reality Thing is Real\"",
    "74": "\"Escape! Leave Me Alone\"",
    "75": "\"I Chosen To be Alive\""
}