{
    "0": "Sudden Shock Sign \"Disappear and reappear\"",
    "2": "Giga Shock Sign \"Disappear and reappear\"",
    "4": "Drugs Sign \"Criss Crossing, Chemicals\"",
    "6": "Drugs Sign \"Criss Crossing, Chemicals and Elixirs\"",
    "8": "Hero's Dilemma Sign \"Evil or Holy Nature\"",
    "10": "Hero's Dilemma Sign \"Evil or Holy Reality\"",
    "12": "Soul Sign \"Soul of Negative and Positive\"",
    "14": "Soul EX Sign \"Soul of Negative and Positive\"",
    "16": "Heart Throbber \"Adventure In The Mind\"",
    "18": "One Eye'd Adventure Sign \"A Mess of Minds\"",
    "20": "Murder Sign \"Eternal Murder Room of Meekly Deaths\"",
    "22": "Artisty Sign \"Pain a Picture of A Feeling\"",
    "24": "True Art Sign \"Drowing in Blue\"",
    "26": "Artsy Top \"Laser do, Amulet See\"",
    "29": "Artsy Top Up \"Painting of a Nerve\"",
    "30": "Artist's Sign \"Insperation\"",
    "34": "Magic Sign \"Instant Bodhi\"",
    "36": "Magic Sign \"Instantaneous Bodhi\"",
    "38": "Magic Sign \"Bullet Golem\"",
    "40": "Magic Sign \"Gigantic Pet Bullet Lifeform\"",
    "42": "Jizo \"Criminal Salvation\"",
    "44": "Jizo \"Hellfire Salvation\"",
    "46": "Bamboo Sign \"Bamboo Spear Dance\"",
    "48": "Bamboo Sign \"Bamboo Crazy Dance\"",
    "50": "Myōga Ginger \"Forget Your Name\"",
    "54": "Broadleaf Sign \"Tanabata Star Festival\"",
    "58": "Myōga Blessing \"Behind You\"",
    "62": "Dance Sign \"Behind Festival\"",
    "66": "Mad Dance \"Tengu-Odoshi\"",
    "68": "Mad Dance \"Frenzied Tengu-Frightening\"",
    "70": "Back Sign \"Halo of the Secret God\"",
    "73": "Back Sign \"Halo of the Absolute Secret God\"",
    "74": "Hidden Summer \"Scorch by Hot Summer\"",
    "76": "Hidden Summer \"Scorched Earth of Abnormal Intense Heat\"",
    "78": "Hidden Fall \"Die of Famine\"",
    "80": "Hidden Fall \"Preta of Abnormal Blight\"",
    "82": "Hidden Winter \"Black Snowman\"",
    "84": "Hidden Winter \"Snowman of Abnormal Snowfall\"",
    "86": "Hidden Spring \"April Wizard\"",
    "88": "Hidden Spring \"Black Magician of Abnormal Falling Petals\"",
    "90": "\"Hidden Breezy Cherry Blossom\"",
    "94": "\"Hidden Perfect Summer Ice\"",
    "98": "\"Hidden Crazy Fall Wind\"",
    "102": "\"Hidden Extreme Winter\"",
    "106": "Sounds of an Info Sign \"Burning Ghosts of Wheel Spirits\"",
    "107": "God's Sacred Song \"Myths and Reality\"",
    "108": "Bullet Dance \"Two-Eyed Typhoon\"",
    "109": "Secret Ceremony \"Reverse Invoker\"",
    "110": "Secret Ceremony \"Rear Shots of Betrayal\"",
    "111": "Agony Sign \"Horrible Nightmare of Omega\"",
    "112": "HeartBound Ceremony \"Laser's To The MoonSide\"",
    "113": "Flare Sign \"Rainbow Flare\"",
    "114": "Scarlet's Burst of Monochrome Storm",
    "115": "Fallen Sign \"Burning Match Sticks\"",
    "116": "Secret Road of The Shrine \"Darkness Rises\"",
    "117": "\"Slit Across The Eye's Burning Broken Star\"",
    "118": "\"Kokuri's and Omega's Nightmare of Dreamland\"",
    "119": "\"Overdriven\""
}