{
    "0": "Sudden Shock Sign \"Disappear and reappear\"",
    "2": "Giga Shock Sign \"Disappear and reappear\"",
    "4": "Drugs Sign \"Criss Crossing, Chemicals\"",
    "6": "Drugs Sign \"Criss Crossing, Chemicals and Elixirs\"",
    "8": "Hero's Dilemma Sign \"Evil or Holy Nature\"",
    "10": "Hero's Dilemma Sign \"Evil or Holy Reality\"",
    "12": "Soul Sign \"Soul of Negative and Positive\"",
    "14": "Soul EX Sign \"Soul of Negative and Positive\"",
    "16": "Heart Throbber \"Adventure In The Mind\"",
    "18": "One Eye'd Adventure Sign \"A Mess of Minds\"",
    "20": "Murder Sign \"Eternal Murder Room of Meekly Deaths\"",
    "22": "Artisty Sign \"Pain a Picture of A Feeling\"",
    "24": "True Art Sign \"Drowing in Blue\"",
    "26": "Artsy Top \"Laser do, Amulet See\"",
    "29": "Artsy Top Up \"Painting of a Nerve\"",
    "30": "Artist's Sign \"Insperation\"",
    "34": "Grabbing light Sign \"Pulling in Light\"",
    "36": "Grabbing light Sign \"Pulling in Light\"",
    "38": "Four of One Kinda Sign \"Silly Orbs Dancing\"",
    "40": "Four of One Kinda Sign \"Silly Orbs Dancing\"",
    "42": "There is Nothing left Sign\"Stepping into Reality\"",
    "44": "There is Nothing left Sign\"Stepping Out of Reality\"",
    "46": "Reflection of Light Sign \"Midi's Stars Dance\"",
    "48": "Reflection of Light Sign \"Midi's Stars Dance\"",
    "50": "Loud and Unfair \"Crossing Out Oxygen\"",
    "54": "Behind Them Sign \"Black Midi's Festival Song\"",
    "58": "Behind Them Sign \"White Midi's Festival Song\"",
    "62": "Duo Sign \"Gray Midi\"",
    "66": "Copy Song Sign \"Tengu-Odoshi\"",
    "68": "Copy Song Sign \"Frenzied Tengu-Frightening\"",
    "70": "Black Sign \"Covered in Ink\"",
    "73": "Monochrome Sign \"Ray of Monochrome\"",
    "74": "Forgotten Summer \"Scorch by Hot Summer\"",
    "76": "Forgotten Summer \"Scorched Earth of Abnormal Intense Heat\"",
    "78": "Reverse Offensive \"Amulet Gods\"",
    "80": "Reverse Offensive \"Amulet Gods\"",
    "82": "Ice and Oil \"Black Snowman\"",
    "84": "Ice and Oil \"Oil The Snowmans Grave\"",
    "86": "April Fools",
    "88": "April Fools",
    "90": "\"Reimu Hakurei sign \"Duplex Barrier\"\"",
    "94": "\"Yuuka Kazami sign \"Lotus Land Mannor\"\"",
    "98": "\"Reimu Hakurei sign \"Story of Eastern WonderLand\"\"",
    "102": "\"Marisa Kirisame sign \"Cold Heart Spark\"\"",
    "106": "Sounds of an Info Sign \"Burning Ghosts of Wheel Spirits\"",
    "107": "God's Sacred Song \"Myths and Reality\"",
    "108": "Forgotten Sign \"Identity Lost\"",
    "109": "Secret Ceremony \"Reverse Invoker\"",
    "110": "Secret Ceremony \"Rear Shots of Betrayal\"",
    "111": "Agony Sign \"Horrible Nightmare of Omega\"",
    "112": "HeartBound Ceremony \"Laser's To The MoonSide\"",
    "113": "Flare Sign \"Rainbow Flare\"",
    "114": "Scarlet's Burst of Monochrome Storm",
    "115": "Fallen Sign \"Burning Match Sticks\"",
    "116": "Secret Road of The Shrine \"Darkness Rises\"",
    "117": "\"Slit Across The Eye's Burning Broken Star\"",
    "118": "\"Kokuri's and Omega's Nightmare of Dreamland\"",
    "119": "\"Overdriven\""
}