{
    "0": "Leaf Sign \"Dagger's into the Fall\"",
    "2": "Fall Sign \"The Broken System of Harvest\"",
    "4": "Fall Sign \"The Fall Sky and a Maiden's Heart\"",
    "6": "Plenty Sign \"Keen eye of the Harvest\"",
    "8": "Bumper Crop \"Quick Grab of Crops\"",
    "10": "Misfortune Sign \"Amulets of a clover\"",
    "12": "Misfortune Sign \"Clover's Misfortune\"",
    "14": "Clover Sign \"Fake Luck\"",
    "16": "Forbidden Luck of one's dream",
    "18": "Flare of Misfortune of a Book",
    "20": "Flare of Misfortune of a Walking Mansion",
    "22": "Forbidden Amulet",
    "24": "True Unlucky Clover Protection",
    "26": "Optics \"Optical Camouflage\"",
    "28": "Optics \"Hydro Camouflage\"",
    "30": "Flood \"Ooze Flooding\"",
    "32": "Flood \"Diluvial Mere\"",
    "33": "Drown \"Trauma in the Glimmering Depths\"",
    "34": "Water Sign \"Kappa's Pororoca\"",
    "36": "Water Sign \"Kappa's Flash Flood\"",
    "37": "Water Sign \"Kappa's Great Illusionary Waterfall\"",
    "38": "Kappa \"Monster Cucumber\"",
    "40": "Kappa \"Exteeeending Aaaaarm\"",
    "41": "Kappa \"Spin the Cephalic Plate\"",
    "42": "Crossroad Sign \"Crossroads of Heaven\"",
    "44": "Crossroad Sign \"Saruta Cross\"",
    "46": "Wind God \"Wind God's Leaf-Veiling\"",
    "48": "Wind God \"Tengu's Fall Wind\"",
    "49": "Wind God \"Storm Day\"",
    "50": "\"Illusionary Dominance\"",
    "51": "\"Illusionary Dominance\"",
    "52": "\"Peerless Wind God\"",
    "53": "Blockade Sign \"Mountain God's Procession\"",
    "55": "Blockade Sign \"Advent of the Divine Grandson\"",
    "56": "Blockade Sign \"Terukuni Shining Through Heaven and Earth\"",
    "57": "Esoterica \"Gray Thaumaturgy\"",
    "59": "Esoterica \"Forgotten Ritual\"",
    "60": "Esoterica \"Secretly Inherited Art of Danmaku\"",
    "61": "Miracle \"Daytime Guest Stars\"",
    "63": "Miracle \"Night with Bright Guest Stars\"",
    "64": "Miracle \"Night with Overly Bright Guest Stars\"",
    "65": "Sea Opening \"The Day the Sea Split\"",
    "67": "Sea Opening \"Moses' Miracle\"",
    "68": "Sea Opening \"Moses' Miracle\"",
    "69": "Preparation \"Star Ritual to Call the Godly Winds\"",
    "71": "Preparation \"Summon Takeminakata\"",
    "73": "Miracle \"God's Wind\"",
    "75": "Great Miracle \"Yasaka's Divine Wind\"",
    "77": "Divine Festival \"Expanded Onbashira\"",
    "79": "Weird Festival \"Medoteko Boisterous Dance\"",
    "80": "Weird Festival \"Medoteko Boisterous Dance\"",
    "81": "Rice Porridge in Tube \"God's Rice Porridge\"",
    "83": "Forgotten Grain \"Unremembered Crop\"",
    "84": "Divine Grain \"Divining Crop\"",
    "85": "Sacrifice Sign \"Misayama Hunting Shrine Ritual\"",
    "87": "Mystery \"Kuzui Clear Water\"",
    "88": "Mystery \"Yamato Torus\"",
    "89": "Heaven's Stream \"Miracle of Otensui\"",
    "91": "Heaven's Dragon \"Source of Rains\"",
    "93": "\"Mountain of Faith\"",
    "95": "\"Divine Virtues of Wind God\"",
    "97": "God Sign \"Beautiful Spring like Suiga\"",
    "98": "God Sign \"Ancient Fate Linked by Cedars\"",
    "99": "God Sign \"Omiwatari that God Walked\"",
    "100": "Party Start \"Two Bows, Two Claps, and One Bow\"",
    "101": "Native God \"Lord Long-Arm and Lord Long-Leg\"",
    "102": "Divine Tool \"Moriya's Iron Ring\"",
    "103": "Spring Sign \"Jade of the Horrid River\"",
    "104": "Frog Hunt \"The Snake Eats the Croaking Frog\"",
    "105": "Native God \"Seven Stones and Seven Trees\"",
    "106": "Native God \"Froggy Braves the Wind and Rain\"",
    "107": "Native God \"Red Frogs of Houei Four\"",
    "108": "\"Suwa War ~ Native Myth vs. Central Myth\"",
    "109": "Scourge Sign \"Mishaguji-sama\"",
	"110":	"Harvester of the moon",
	"112":	"Harvester of the Earth"
}
