{
    "0": "Leaf Sign \"Dagger's into the Fall\"",
    "2": "Fall Sign \"The Broken System of Harvest\"",
    "4": "Fall Sign \"The Fall Sky and a Maiden's Heart\"",
    "6": "Plenty Sign \"Keen eye of the Harvest\"",
    "8": "Bumper Crop \"Quick Grab of Crops\"",
    "10": "Misfortune Sign \"Amulets of a clover\"",
    "12": "Misfortune Sign \"Clover's Misfortune\"",
    "14": "Clover Sign \"Fake Luck\"",
    "16": "Forbidden Luck of one's dream",
    "18": "Flare of Misfortune of a Book",
    "20": "Flare of Misfortune of a Walking Mansion",
    "22": "Forbidden Amulet",
    "24": "True Unlucky Clover Protection",
    "26": "Optics \"Optical Camouflage\"",
    "28": "Optics \"Hydro Camouflage\"",
    "30": "Flood \"Ooze Flooding\"",
    "32": "Flood \"Diluvial Mere\"",
    "33": "Drown \"Trauma in the Glimmering Depths\"",
    "34": "Water Sign \"Kappa's Pororoca\"",
    "36": "Water Sign \"Kappa's Flash Flood\"",
    "37": "Water Sign \"Kappa's Great Illusionary Waterfall\"",
    "38": "Kappa \"Monster Cucumber\"",
    "40": "Kappa \"Exteeeending Aaaaarm\"",
    "41": "Kappa \"Spin the Cephalic Plate\"",
    "42": "Speed Sign \"Take aim and cry\"",
    "44": "AB Speed Sign \"Crying Crows of a Murder\"",
    "46": "Fall of Wind God \"Wind God's Leaf-Veiling\"",
    "48": "Fall of Wind God  \"Tengu's Fall Wind\"",
    "49": "Fall of Wind God  \"Tengu's Day\"",
    "50": "\"I need MORE Speed\"",
    "51": "\"I need MORE Speed+\"",
    "52": "\"Faster than a frame of light\"",
    "53": "Windy bubble Sign \"Mountain God's Procession\"",
    "55": "Windy bubble Sign \"Advent of the Divine Grandson\"",
    "56": "Windy bubble Sign \"Terukuni Shining Through Heaven and Earth\"",
    "57": "Esoterica Of copies \"Gray Thaumaturgy\"",
    "59": "Esoterica Of copies \"Forgotten Ritual\"",
    "60": "Esoterica Of copies \"Secretly Inherited Art of Danmaku\"",
    "61": "Miracle Of copies \"Fake days\"",
    "63": "Miracle Of copies \"Faking the complete ownership\"",
    "64": "Miracle Of copies \"Faking the complete ownership\"",
    "65": "\"The Day the Sea Split\"",
    "67": "\"Moses' Miracle\"",
    "68": "\"Moses' Miracle\"",
    "69": "Star dust collection",
    "71": "Star dust stom of collection",
    "73": "unheard of copycat \"God's Wind\"",
    "75": "unheard of copycat Tengu's dream \"Yasaka's Divine Wind\"",
    "77": "Kaizo Festival \"Trapped more than once\"",
    "79": "Kaizo Festival \"Medoteko Boisterous Dance\"",
    "80": "Kaizo Festival \"Medoteko Boisterous Dance\"",
    "81": "Kaizo's Rice Porridge in Tube \"God's Rice Porridge\"",
    "83": "Unforgiven Grain \"Unremembered Crop\"",
    "84": "URA Grain \"Divining Crop\"",
    "85": "Kaizo Sign \"Misayama Hunting Shrine Ritual\"",
    "87": "Mystery \"Kuzui Clear Water\"",
    "88": "Mystery \"Yamato Torus\"",
    "89": "Kaizo's Stream \"The way of the knife\"",
    "91": "Kaizo's Dragon \"Deepen the cut of knife\"",
    "93": "\"Mountain of Kaizo goddesses\"",
    "95": "\"Mountain of Kaizo goddesses\"",
    "97": "God Sign \"Criss Cross lane\"",
    "98": "True God Kaizo Sign \"Mountain of Kaizo Intense Kaizo\"",
    "99": "God Sign \"Water Monster's lake\"",
    "100": "Simple yet different Dream \"Two Arches and Two Flaming Idea's\"",
    "101": "Native God \"Unimaginable Kaizo of Embodiment of The Froggy Goddess\"",
    "102": "Divine Tool \"Moriya's Rainbow Iron Ring\"",
    "103": "Two Long Wars Sign \"Too lazy to Tell History\"",
    "104": "Frog Hunt \"The lake of Flare and Dare's\"",
    "105": "Native God \"Broken Goddesses Seventh tree\"",
    "106": "Fall God \"Falling of Dreaming Ice\"",
    "107": "The Second Galaxy Sign \"Frog Commet\"",
    "108": "\"Suwa War ~ Native Myth vs. Central Myth\"",
    "109": "Rainbow Frog Sign \"The Last Cry of a God\"",
	"110":	"Harvester of the moon",
	"112":	"Harvester of the Earth"
}
