{
    "0+Boss00BossCard1+0": "Spirit Sign \"Rampant Yin-Yang Orbs\"",
    "0+Boss00BossCard1H+0": "Spirit Sign \"Trampling Yin-Yang Orbs\"",
    "1+Boss00BossCard1+0": "Star Sign \"Shoot The Beast\"",
    "1+Boss00BossCard1H+0": "Star Sign \"Shoot The Beast King\"",
    "4+Boss00BossCard1+0": "Spinning Top \"Koma-Inu Spin\"",
    "4+Boss00BossCard1+4": "Spinning Top \"Koma-Inu Giant Slalom Spin\"",
    "5+Boss00BossCard1+0": "Gemstone \"Jewel Rain\"",
    "5+Boss00BossCard1+4": "Gemstone \"Jewel Rain\"",
    "6+Boss00BossCard1+0": "Bullet Sign \"Rabbit Shooting\"",
    "0+BossCard2+0": "\"All The Stored Up Yin-Yang Orbs\"",
    "0+BossCard3+0": "\"No Mercy In Exorcizing Demonic Beasts\"",
    "2+Boss00BossCard1+0": "Wind Sign \"Wind Rider\"",
    "2+Boss00BossCard1+6": "Wind Sign \"Wind Master\"",
    "3+Boss00BossCard1+0": "Shikigami \"Still-Hunter Chen”",
    "3+Boss00BossCard1+6": "Shikigami \"Multi-Still Hunter\"",
    "7+Boss00BossCard1+0": "Dead Spirit \"Fairy of The Dead\"",
    "8+BossCard1+0": "Kuda-gitsune \"Cylinder Fox\"",
    "9+BossCard1+0": "Tanuki Sign \"Fall For The Greedy Animal Spirits!\"",
    "10+BossCard1+0": "Tortoise Sign \"Tortoiseshell Hell\"",
    "10+BossCard2+0": "Tortoise Sign \"Jidiao Great Barrier\"",
    "10+BossCard3+0": "Dragon Sign \"Dragon Crest Bullets\"",
    "11+BossCard1+0": "Heavenly Stellar Steed \"Pegasus Cross\"",
    "11+BossCard2+0": "Heavenly Stellar Steed \"Pegasus Starmine\"",
    "11+BossCard3+0": "\"Last Shoot\"",
    "12+BossCard1+0": "Old Grudge \"Gorge Riser\"",
    "12+BossCard2+0": "\"Absorber Phantom\"",
    "12+BossCard3+0": "\"Bottom of Gluttony\"",
    "13+BossCard1+0": "Oni Sign \"Deep Fog Drunk Oni\"",
    "13+BossCard2+0": "Oni Sign \"Silent Deep Fog Drunk Oni\"",
    "13+BossCard3+0": "\"Beautiful Hell Danmaku Night Parade\"",
    "14+BossCard1+0": "Monkey Strike \"Monkey Magic\"",
    "15+BossCard1+0": "Three Heads \"Cerberus Fire\"",
    "16+BossCard1+0": "Cursed Blood \"Cursed Devil\"",
    "17+BossCard1+0": "Executor \"Jailbreak Stalker\"",
    "18+BossCard1+0": "\"Pure Spirit Shot\"",
    "18+BossCard2+0": "\"Insentient Pure Spirit Shot\"",
    "18+BossCard3+0": "\"Kingdom of Lost Sheep\""
}