{
    "0": "Butterfly Snake Sign \"The Snake's sharp eye\"",
    "2": "Butterfly Snake Sign \"The Snake's Sharp Eye\"",
    "4": "Butterfly Sign \"Fluttering Summer Deluxe\"",
    "6": "Butterfly Sign \"Midsummer Wingbeats Deluxe\"",
    "8": "LavaFall Sign \"Singing In The ''Rain''\"",
    "10": "LavaFall Sign \"Singing In The ''Pool''\"",
    "12": "volcano Sign \"Cooked Up Good\"",
    "14": "volcano Sign \"The Eternal Uproar\"",
    "16": "Self Explosion Sign \"Square of A Yearly Murder\"",
    "18": "Self Explosion Sign \"Unheard of Tatic!\"",
    "20": "Lunatic Sign \"Surprise Lunatic Clown\"",
    "22": "Shrine Dog Sign \"ShrineMaiden's Strong Dog\"",
    "24": "Tails Sign \"The Dog After It's Own Tail\"",
    "26": "Spinning Top \"Koma-Inu Spin\"",
    "29": "Spinning Top \"Curl Up and Die\"",
    "30": "Koma Sign \"Solitary A-Un Breathing\"",
    "34": "Dream Sign \"Spinning Dreamer\"",
    "36": "Dream LD Sign \"Lucid Gem Snap\"",
    "38": "Red Lucid Gem Fruit \"Red Lucid Gem Spirit Bomb\"",
    "40": "Red Lucid Gem Fruit \"Lucid Gem Savour's Taste\"",
    "42": "Lucid Gem Fruit \"Hero's Of Reality\"",
    "44": "Lucid Gem Fruit \"Fruit Of Stolen Abilities But Stronger\"",
    "46": "Greenie Sign \"Dream like Reality\"",
    "48": "Brutal Dream Sign \"Reality Wishy Washy\"",
    "50": "Soul Steal \"Spinny Fake Peices\"",
    "54": "Avalan Sign \"Fallen Snow or Ice\"",
    "58": "Butt from Behind \"Behind You\"",
    "62": "''French and Austrian Yelling''",
    "66": "''French and Austrian Yelling'' - E N",
    "68": "''French and Austrian Yelling'' - H L",
    "70": "Void Sign \"Season Hidden Zenith\"",
    "73": "Zenith's Void",
    "74": "Sweet Summer \"Trapped to Eat a Berry\"",
    "76": "Taboo Summer \"Summer of Eternal Harvest\"",
    "78": "Fall \"Frozen Heart\"",
    "80": "Fall \"The Fall of One's True Heart\"",
    "82": "Hidden Winter \"Black Snowman\"",
    "84": "Hidden Winter \"Snowman of Abnormal Snowfall\"",
    "86": "Spring \"Cherry Blooming\"",
    "88": "Blooming Dreamer",
    "90": "The Eternal Blooming Eye's",
    "94": "The Strongest and The Greatest Humans Around Even The True Ultimate Thousand Knifes Of WvCwHH Little Power",
    "98": "Crossing The Forever Falling Love",
    "102": "Blizzard Of A Fake Lucid Dream",
    "106": "Drum Dance \"Powerful Cheers\"",
    "107": "Mad Dance \"Crazy Backup Dance\"",
    "108": "Bullet Dance \"Twin Typhoons\"",
    "109": "Gap Sign \"Warp To A Another Side\"",
    "110": "Higher Gap Sign \"3 Blooming Branches\"",
    "111": "Inside Sign \"Maw Of The Creature\"",
    "112": "Secret Gap \"Blooming of A Shrine\"",
    "113": "Violet Vortex \"Insanity of Universes\"",
    "114": "Colourful Eye \"Colourful Shooting -Alpha-\"",
    "115": "High Speed Fabric Tears In Space",
    "116": "Illusion of Repeated Dimensional Rupture",
    "117": "\"Some Yokai In Sleeping Paradise Anti Matter\"",
    "118": "\"Eternal Damnation\"",
	"119": "\"Dreaming of A Dull Universe\""
}