{
    "0": "Butterfly Snake Sign \"The Snake's sharp eye\"",
    "2": "Butterfly Snake Sign \"The Snake's Sharp Eye\"",
    "4": "Butterfly Sign \"Fluttering Summer Deluxe\"",
    "6": "Butterfly Sign \"Midsummer Wingbeats Deluxe\"",
    "8": "LavaFall Sign \"Singing In The ''Rain''\"",
    "10": "LavaFall Sign \"Singing In The ''Pool''\"",
    "12": "volcano Sign \"Cooked Up Good\"",
    "14": "volcano Sign \"The Eternal Uproar\"",
    "16": "Self Explosion Sign \"Square of A Yearly Murder\"",
    "18": "Self Explosion Sign \"Unheard of Tatic!\"",
    "20": "Lunatic Sign \"Surprise Lunatic Clown\"",
    "22": "Shrine Dog Sign \"ShrineMaiden's Strong Dog\"",
    "24": "Tails Sign \"The Dog After It's Own Tail\"",
    "26": "Spinning Top \"Koma-Inu Spin\"",
    "29": "Spinning Top \"Curl Up and Die\"",
    "30": "Koma Sign \"Solitary A-Un Breathing\"",
    "34": "Magic Sign \"Instant Bodhi\"",
    "36": "Magic Sign \"Bodhi in an Instant\"",
    "38": "Magic Sign \"Bullet Golem\"",
    "40": "Magic Sign \"Gigantic Pet Bullet Lifeform\"",
    "42": "Jizo \"Criminal Salvation\"",
    "44": "Jizo \"Hellfire Salvation\"",
    "46": "Bamboo Sign \"Bamboo Spear Dance\"",
    "48": "Bamboo Sign \"Bamboo Crazy Dance\"",
    "50": "Myōga Ginger \"Forget Your Name\"",
    "54": "Broadleaf Sign \"Tanabata Star Festival\"",
    "58": "Myōga Blessing \"Behind You\"",
    "62": "Dance Sign \"Behind Festival\"",
    "66": "Mad Dance \"Tengu-odoshi\"",
    "68": "Mad Dance \"Frenzied Tengu-Frightening\"",
    "70": "Back Sign \"Halo of the Secret God\"",
    "73": "Back Sign \"Halo of the Absolute Secret God\"",
    "74": "Hidden Summer \"Scorch By Hot Summer\"",
    "76": "Hidden Summer \"Scorched Earth of Abnormal Intense Heat\"",
    "78": "Hidden Fall \"Die of Famine\"",
    "80": "Hidden Fall \"Preta of Abnormal Blight\"",
    "82": "Hidden Winter \"Black Snowman\"",
    "84": "Hidden Winter \"Snowman of Abnormal Snowfall\"",
    "86": "Hidden Spring \"April Wizard\"",
    "88": "Hidden Spring \"Black Magician of Abnormal Falling Petals\"",
    "90": "\"Hidden Breezy Cherry Blossom\"",
    "94": "\"Hidden Perfect Summer Ice\"",
    "98": "\"Hidden Crazy Fall Wind\"",
    "102": "\"Hidden Extreme Winter\"",
    "106": "Drum Dance \"Powerful Cheers\"",
    "107": "Mad Dance \"Crazy Backup Dance\"",
    "108": "Bullet Dance \"Twin Typhoons\"",
    "109": "Secret Ceremony \"Reverse Invoker\"",
    "110": "Secret Ceremony \"Rear Shots of Betrayal\"",
    "111": "Secret Ceremony \"Danmaku Dupion\"",
    "112": "Secret Ceremony \"Fire of Ena\"",
    "113": "Secret Ceremony \"Kyōgen of the Back Door\"",
    "114": "Secret Ceremony \"Matarah Dukkha\"",
    "115": "Secret Ceremony \"Sword of the Seven Stars\"",
    "116": "Secret Ceremony \"Performers Unattached to Society\"",
    "117": "\"The Back Face's Dark Sarugaku\"",
    "118": "\"Anarchy Bullet Hell\""
}