{
    "0": "Stolen bullet's Sign \"Speed Strike Dango\"",
    "2": "Crossed Dimensions Sign \"Just Easy Snowy Shooting Initial Cold Attack\"",
    "5": "Crossed Dimensions Sign \"Just Easy Snowy Shooting Initial Cold Attack\"",
    "6": "Close Door Sign \"Inside of a bullet\"",
    "9": "Close Door Sign \"Inside the soul of a bullet\"",
    "10": "Rabbit Sign \"Party Dango\"",
    "12": "Rabbit Sign \"Dash Dash Dash to dango\"",
    "14": "Rabbit Sign \"Staba Dango\"",
    "18": "Up-High Sky \"8 snowstorms\"",
    "21": "Up-High Sky \"8 rainbow snowstorms\"",
    "22": "Dream Sign \"Fake Nightmare of the Dream Realem\"",
    "24": "Dream Sign \"Fake Nightmare of DreamLand\"",
    "26": "Dream Sign \"Indigo Dream of Anxiety\"",
    "28": "Dream Sign \"Indigo Three-Layered Dream of Anxiety\"",
    "29": "Dream Sign \"Spin Sping around the dreams\"",
    "30": "Dream Sign \"Where to go where to go?\"",
    "32": "Dream Sign \"Where do you go where do you go!?\"",
    "34": "Dream Sign \"Dream Catcher\"",
    "36": "Dream Sign \"Azure Dream Catcher\"",
    "37": "Dream Sign \"Losing Oneself in a Dream\"",
    "38": "Dreaming Sign \"Ultramarine Lunatic Dream of song and ice\"",
    "42": "Orb Sign \"One wings blast to the new year\"",
    "44": "Orb Sign \"One wings blast to the new Century\"",
    "46": "Orb Sign \"Embodyment of impure deeds\"",
    "48": "Orb Sign \"Embodyment of the impure body\"",
    "50": "Orb Sign \"Taste the orbs of dreams\"",
    "52": "Orb Sign \"Taste the orbs of the elder gods\"",
    "54": "Sepiroth Sign\"Blazing pillars\"",
    "58": "Hell and Moon Sign \"Hell is BURSTING the MOON\"",
    "60": "Hell and Moon Sign \"Hell is BURSTING the MOON\"",
    "62": "Fun Sign \"Bounce and star at the sky\"",
    "64": "Hell Sign \"Star and Stripe\"",
    "66": "Hellfire \"Graze or not?\"",
    "69": "Hellfire \"infire Grazing?\"",
    "70": "Inferno \"Striped clown!\"",
    "74": "\"Fake Stars and Bursts\"",
    "76": "\"Fake Stars and Bursts\"",
    "78": "\"the love inside a snow drop\"",
    "82": "\"Murder of the one I love\"",
    "86": "\"143 years of I love you\"",
    "88": "\"143 years of I love you\"",
    "90": "\"Pop the star of shiver star\"",
    "94": "\"Bland and unchanged\"",
    "98": "\"Make up or die up\"",
    "101": "\"Make up or die up\"",
    "102": "Pure Sign \"Before the Mystic dreams\"",
    "104": "Lotus Land Story Sign \"9800 years of torment\"",
    "106": "Pinkbow \"Over The Pink-Bow\"",
    "107": "Fishes to Dishes \"Shark Scales\"",
    "108": "Dream \"Dreaming for 4,000 years\"",
    "109": "Burning Card sign \"Barrier to another Hell\"",
    "110": "Laser point \"The Emodiment of Goddess's Dream\"",
    "111": "Dream sign \"Wake up from Slumber\"",
    "112": "\"Grow Frow Crow My Rage\"",
    "113": "Otherworld \"Spot the darkness\"",
    "114": "Dancing sign \"Eternal dancing Goddess\"",
    "115": "Fake eyes \"Eye see you!\"",
    "116": "\"Blind Rage\"",
    "117": "\"Flip Flop the worlds table\"",
    "118": "\"Eternal dancing engine Friends\"",
    "45": "Orb Sign \"Disorderly Flock's Duplex Curse\""
}