{
    "0": "Beckon Sign \"Danmaku Business Boom\"",
    "4": "Beckon Sign \"Shoot Away Disaster, Beckon in Fortune\"",
    "8": "Forest Sign \"Tree-Veiling Technology\"",
    "10": "Forest Sign \"Extreme Tree-Veiling Technology\"",
    "11": "Forest Sign \"True Tree-Veiling Technology\"",
    "12": "Forest Sign \"Innermost Forest Region\"",
    "14": "Forest Sign \"Extreme Innermost Forest Region\"",
    "15": "Forest Sign \"True Innermost Forest Region\"",
    "16": "Leaf Skill \"Green Spiral\"",
    "18": "Leaf Skill \"Green Cyclone\"",
    "19": "Leaf Skill \"Green Tornado\"",
    "20": "Mountain Sign \"Heaven-Shaking Kumomagusa\"",
    "22": "Mountain Apparition \"Astonishing Kumomagusa\"",
    "24": "Mountain Sign \"Usuyukisou Shining with Bewitching Light\"",
    "26": "Mountain Apparition \"Usuyukisou of Thronging Crowds of Youma\"",
    "28": "Mountain Flower \"Komakusa of Massacre\"",
    "30": "Mountain Flower \"Mountain Queen of Massacre\"",
    "32": "Sealing Orb Sign \"Shrine Maiden's Dance\"",
    "35": "Pure Sealing Sign \"Yin-Yang Divine Sealing Orbs\"",
    "40": "\"Ying-Yang Storm of The Hakurei Shrine Maiden Last Attack\"",
    "36": "Get Caught and Hit \"Shrine Maiden of the Blue Shrine\"",
    "38": "Strong Will sign \"Black and White also Blue Shrine Maiden\"",
    "68": "\"Bullet Market\"",
    "70": "\"High Density Bullet Market\"",
    "71": "\"Danmaku Free Market\"",
    "76": "\"Bullet Dominion\"",
    "78": "\"Tyrannical Bullet Dominion\"",
    "79": "\"Inhumane Bullet Dominion\"",
    "92": "Mining \"Shield Method of the Youkai\"",
    "91": "Mining \"Mine Blast\"",
    "90": "Mining \"Ever-Accumulating Mine Dump\"",
    "87": "Kodoku \"Cannibalistic Insect\"",
    "88": "Kodoku \"Cave Swarmer\"",
    "89": "Kodoku \"Sky Pendra\"",
    "93": "Oomukade \"Snake Eater\"",
    "94": "Oomukade \"Dragon Eater\"",
    "95": "\"Kodoku Gourmet\"",
    "96": "\"Mushihime-sama's Resplendent and Restless Daily Life\"",
    "80": "\"Asylum of Danmaku\"",
    "84": "Fox Sign \"Fox Winder\"",
    "85": "Kuda-gitsune \"Cylinder Fox\"",
    "60": "\"An Offering to the Ownerless\"",
    "44": "Calamitous Star \"Dance of Star-Sparked Wildfire\"",
    "46": "Calamitous Star \"Wild Dance of Star-Sparked Wildfire\"",
    "48": "Stellar Wind \"Dance of Dazzling Iridescence\"",
    "50": "Stellar Wind \"Wild Dance of Dazzling Iridescence\"",
    "56": "Rainbow Illumination \"Clear and Tranquil Wind and Moon\"",
    "52": "Luminous Horse \"Dance of Sky-Racing Heavenly Steeds\"",
    "54": "Luminous Horse \"Wild Dance of Sky-Racing Heavenly Steeds\"",
    "86": "Stellar Fox \"Dance of Heavenly Foxes and Dragon Stars\"",
    "64": "\"Danmaku Hoarder's Obsession\"",
    "72": "\"Rainbow Ring of People\""
}