{
    "0": "Frost Sign \"Frost Falls\"",
    "1": "Frost Sign \"Icy Star Dust\"",
    "2": "Cold Sign \"Lingering Cold -Easy-\"",
    "3": "Cold Sign \"Lingering Cold\"",
    "4": "Cold Sign \"Lingering Cold -Hard-\"",
    "5": "Cold Sign \"Lingering Cold -Lunatic-\"",
    "6": "Winter Sign \"Flower Wither Away -Easy-\"",
    "7": "Winter Sign \"Flower Wither Away\"",
    "8": "White Sign \"Undulation Ray\"",
    "9": "Mystic Sign \"Table-Turning\"",
    "10": "Hermit Sign \"Fenghuang Egg -Easy-\"",
    "11": "Hermit Sign \"Fenghuang Egg\"",
    "12": "Hermit Sign \"Fenghuang's Spread Wings\"",
    "13": "Hermit Sign \"Fenghuang's Spread Wings -Lunatic-\"",
    "14": "Shikigami Sign \"Soaring Seiman -Easy-\"",
    "15": "Shikigami Sign \"Soaring Seiman\"",
    "16": "Yin Yang \"Douman-Seiman\"",
    "17": "Yin Yang \"Seiman-Daimon\"",
    "18": "Heaven Sign \"Tianxian's Rumbling -Easy-\"",
    "19": "Heaven Sign \"Tianxian's Rumbling\"",
    "20": "Flight Sign \"Soaring Idaten\"",
    "21": "Servant Sign \"Gouhou-Tendou's Wild Dance\"",
    "22": "Hermit Sign \"Shikai Immortality -Easy-\"",
    "23": "Hermit Sign \"Shikai Immortality\"",
    "24": "Oni Sign \"Kimon Konjin\"",
    "25": "Direction Sign \"Kimontonkou\"",
    "26": "Puppeteer Sign \"Maiden's Bunraku\"",
    "27": "Puppeteer Sign \"Maiden's Bunraku -Lunatic-\"",
    "28": "Blue Sign \"Fraternal French Dolls -Easy-\"",
    "29": "Blue Sign \"Fraternal French Dolls\"",
    "30": "Blue Sign \"Fraternal French Dolls -Hard-\"",
    "31": "Blue Sign \"Fraternal Orléans Dolls\"",
    "32": "Scarlet Sign \"Red-Haired Dutch Dolls -Easy-\"",
    "33": "Scarlet Sign \"Red-Haired Dutch Dolls\"",
    "34": "White Sign \"Chalk-White Russian Dolls\"",
    "35": "White Sign \"Chalk-White Russian Dolls -Lunatic-\"",
    "36": "Darkness Sign \"Foggy London Dolls -Easy-\"",
    "37": "Darkness Sign \"Foggy London Dolls\"",
    "38": "Cycle Sign \"Samsaric Tibetan Dolls\"",
    "39": "Elegant Sign \"Spring Kyoto Dolls\"",
    "40": "Malediction \"Magically Luminous Shanghai Dolls -Easy-\"",
    "41": "Malediction \"Magically Luminous Shanghai Dolls\"",
    "42": "Malediction \"Magically Luminous Shanghai Dolls -Hard-\"",
    "43": "Malediction \"Hanged Hourai Dolls\"",
    "44": "Noisy Sign \"Phantom Dinning -Easy-\"",
    "45": "Noisy Sign \"Phantom Dinning\"",
    "46": "Noisy Sign \"Live Poltergeist\"",
    "47": "Noisy Sign \"Live Poltergeist -Lunatic-\"",
    "48": "String Performance \"Guarneri del Gesù -Easy-\"",
    "49": "String Performance \"Guarneri del Gesù\"",
    "50": "Divine Strings \"Stradivarius\"",
    "51": "Fake Strings \"Pseudo Stradivarius\"",
    "52": "Trumpet Spirit \"Hino Phantasm -Easy-\"",
    "53": "Trumpet Spirit \"Hino Phantasm\"",
    "54": "Nether Trumpet \"Ghost Clifford\"",
    "55": "Nether Trumpet \"Ghost Clifford -Lunatic-\"",
    "56": "Nether Keys \"Fazioli Nether Performance -Easy-\"",
    "57": "Nether Keys \"Fazioli Nether Performance\"",
    "58": "Key Spirit \"Bösendorfer Divine Performance\"",
    "59": "Key Spirit \"Bösendorfer Divine Performance -Lunatic-\"",
    "60": "Funeral Concert \"Prism Concerto -Easy-\"",
    "61": "Funeral Concert \"Prism Concerto\"",
    "62": "Noisy Funeral \"Stygian Riverside\"",
    "63": "Noisy Funeral \"Stygian Riverside -Lunatic-\"",
    "64": "Great Funeral Concert \"Spirit Wheel Concerto Grosso -Easy-\"",
    "65": "Great Funeral Concert \"Spirit Wheel Concerto Grosso\"",
    "66": "Great Funeral Concert \"Spirit Wheel Concerto Grosso: Revised\"",
    "67": "Great Funeral Concert \"Spirit Wheel Concerto Grosso: Wondrous\"",
    "68": "Ghost Sword \"Fasting of the Young Preta -Easy-\"",
    "69": "Ghost Sword \"Fasting of the Young Preta\"",
    "70": "Preta Sword \"Scroll of the Preta Realm\"",
    "71": "Hungry King Sword \"Ten Kings' Retribution on the Preta\"",
    "72": "Hell Realm Sword \"Two Hundred Yojana in One Slash -Easy-\"",
    "73": "Hell Realm Sword \"Two Hundred Yojana in One Slash\"",
    "74": "Hellfire Sword \"Karmic Winds of Afterimages\"",
    "75": "Hell God Sword \"Karmic Winds Instant-Divine Severance\"",
    "76": "Animal Realm Sword \"Karmic Punishment of the Idle and Unfocused -Easy-\"",
    "77": "Animal Realm Sword \"Karmic Punishment of the Idle and Unfocused\"",
    "78": "Asura Sword \"Obsession with the Present World\"",
    "79": "Asura Sword \"Obsession with the Present World -Lunatic-\"",
    "80": "Human Realm Sword \"Fantasy of Entering Enlightenment -Easy-\"",
    "81": "Human Realm Sword \"Fantasy of Entering Enlightenment\"",
    "82": "Human Era Sword \"Great Enlightenment Appearing and Disappearing\"",
    "83": "Human God Sword \"Constancy of the Conventional Truth\"",
    "84": "Heaven Sword \"Five Signs of the Dying Deva -Easy-\"",
    "85": "Heaven Sword \"Five Signs of the Dying Deva\"",
    "86": "Deva Realm Sword \"Displeasure of the Seven Hakus\"",
    "87": "Heaven God Sword \"Three Kons, Seven Hakus\"",
    "88": "Six Realms Sword \"A Single Thought and Infinite Kalpas -Easy-\"",
    "89": "Six Realms Sword \"A Single Thought and Infinite Kalpas\"",
    "90": "Six Realms Sword \"A Single Thought and Infinite Kalpas -Hard-\"",
    "91": "Six Realms Sword \"A Single Thought and Infinite Kalpas -Lunatic-\"",
    "92": "Dead Village \"Death of One's Home -Wandering Soul-\"",
    "93": "Dead Village \"Death of One's Home -Past Sin-\"",
    "94": "Dead Village \"Death of One's Home -Trackless Path-\"",
    "95": "Dead Village \"Death of One's Home -Suicide-\"",
    "96": "Deadly Dance \"Law of Mortality -Bewilderment-\"",
    "97": "Deadly Dance \"Law of Mortality -Dead Butterfly-\"",
    "98": "Deadly Dance \"Law of Mortality -Poisonous Moth-\"",
    "99": "Deadly Dance \"Law of Mortality -Demon World-\"",
    "100": "Flowery Soul \"Ghost Butterfly\"",
    "101": "Flowery Soul \"Swallowtail Butterfly\"",
    "102": "Flowery Soul \"Deep-Rooted Butterfly\"",
    "103": "Flowery Soul \"Butterfly Delusion\"",
    "104": "Subtle Melody \"Repository of Hirokawa -Grazing Spirit-\"",
    "105": "Subtle Melody \"Repository of Hirokawa -Grazing Spirit-\"",
    "106": "Subtle Melody \"Repository of Hirokawa -Grazing Spirit-\"",
    "107": "Subtle Melody \"Repository of Hirokawa -Grazing Spirit-\"",
    "108": "Sleeping Cherry Blossom Sign \"Perfect Ink-Black Cherry Blossom -Seal-\"",
    "109": "Sleeping Cherry Blossom Sign \"Perfect Ink-Black Cherry Blossom -Self-Loss-\"",
    "110": "Sleeping Cherry Blossom Sign \"Perfect Ink-Black Cherry Blossom -Spring Sleep-\"",
    "111": "Sleeping Cherry Blossom Sign \"Perfect Ink-Black Cherry Blossom -Bloom-\"",
    "112": "\"Resurrection Butterfly -100%% Reflowering-\"",
    "113": "\"Resurrection Butterfly -125%% Reflowering-\"",
    "114": "\"Resurrection Butterfly -150%% Reflowering-\"",
    "115": "\"Resurrection Butterfly -200%% Reflowering-\"",
    "116": "Colourfull Oni Sign \"Blue Oni, Red Oni, Yellow Oni & Green Oni\"",
    "117": "Kishin \"Soaring Bishamonten\"",
    "118": "Shikigami \"Senko Witness\"",
    "119": "Shikigami \"Four General Gods Of a Old System\"",
    "120": "Shiki Brilliance \"Kitsune-Tanuki Youkai Laser\"",
    "121": "Shiki Brilliance \"Charming Siege Full Form\"",
    "122": "Shiki Brilliance \"Princess Tenko's Sun Fall\"",
    "123": "Shiki Shot \"Buddhist Recollection of Reincarnation\"",
    "124": "Shiki Shot \"Contact of a Old Systems Flower\"",
    "125": "Shikigami Summon \"Chen - Hard -\"",
    "126": "\"Contract's From Master Yukari\"",
    "127": "Illusion God \"Descent of Iizuna Gongen\"",
    "128": "Shikigami \"Protection of Zenki and Goki\"",
    "129": "Yakumo's Glory to The Master",
    "130": "Barrier \"Curse of Dreams and Reality\"",
    "131": "Barrier \"Balance of Motion and Stillness\"",
    "132": "Barrier \"Mesh of Light and Darkness\"",
    "133": "Evil Spirits \"Dreamland of Straight and Curve\"",
    "134": "Evil Spirits \"Yukari Yakumo's Spiriting Away\"",
    "135": "Evil Spirits \"Bewitching Butterfly Living in the Zen Temple\"",
    "136": "Sinister Spirits \"Double Black Death Butterfly\"",
    "137": "Shikigami \"Ran Yakumo\"",
    "138": "\"Boundary of Humans and Youkai\"",
    "139": "Barrier \"Boundary of Life and Death\"",
    "140": "Yukari's Arcanum \"Danmaku Barrier\""
}