{
    "0": "Moon Sign \"Moonlight Dancing Rice Ray\"",
    "1": "Path Sign \"Sruck on Path\"",
    "2": "Yokai of Darkness \"Rumia's final fight\"",
    "3": "Ice Sign \"Icicle Wall\"",
    "4": "Snowflake Sign \"SnowFlake Spinner\"",
    "5": "Freeze Sign \"Perfect Freeze Omega\"",
    "6": "Snow Sign \"Diamond Dash & Freeze\"",
    "7": "Flower Sign \"Gorgeous Sweet Flower\"",
    "8": "Flower Sign \"Selaginella 18\"",
    "9": "Aqua and Jade Sign \"Jaded Life Night\"",
    "10": "Illusion Sign \"Imaginary Flower Yumekazura\"",
    "11": "Colorful Sign \"Colorful Rain\"",
    "12": "Colorful Sign \"Vivid Chaotic Dance\"",
    "13": "Colorful Sign \"Dazzling Color Typhoon\"",
    "14": "Fire Sign \"Agni Shine\"",
    "15": "Water Sign \"Princess Undine\"",
    "16": "Wood Sign \"Sylphy Horn\"",
    "17": "Earth Sign \"Lazy Trilithon\"",
    "18": "Metal Sign \"Metal Fatigue\"",
    "19": "Fire Sign \"Agni Shine High Level\"",
    "20": "Wood Sign \"Sylphy Horn High Level\"",
    "21": "Earth Sign \"Lazy Trilithon High Level\"",
    "22": "Fire Sign \"Agni Radiance\"",
    "23": "Water Sign \"Bury In Lake\"",
    "24": "Wood Sign \"Green Storm\"",
    "25": "Earth Sign \"Trilithon Shake\"",
    "26": "Metal Sign \"Silver Dragon\"",
    "27": "Fire & Earth Sign \"Lava Cromlech\"",
    "28": "Wood & Fire Sign \"Forest Blaze\"",
    "29": "Water & Wood Sign \"Water Elf\"",
    "30": "Metal & Water Sign \"Mercury Poison\"",
    "31": "Earth & Metal Sign \"Emerald Megalith\"",
    "32": "Conjuring \"Misdirection\"",
    "33": "Conjuring \"Mesmerizing Misdirection\"",
    "34": "Illusion Existence \"Clock Corpse\"",
    "35": "Illusion Image \"Luna Clock\"",
    "36": "Maid Secret Skill \"Manipulating Doll\"",
    "37": "Illusion Phantom \"Jack the Ludo Bile\"",
    "38": "Illusion World \"The World\"",
    "39": "Maid Secret Skill \"Killing Doll\"",
    "40": "Conjuring \"Eternal Meek\"",
    "41": "Heaven's Punishment \"Star of David\"",
    "42": "Nether Sign \"Scarlet Netherworld\"",
    "43": "Curse \"Curse of Vlad Țepeș\"",
    "44": "Scarlet Sign \"Scarlet Shoot\"",
    "45": "\"Red Magic\"",
    "46": "God's Punishment \"Young Demon Lord\"",
    "47": "Hell Sign \"Mountain of a Thousand Needles\"",
    "48": "Divine Art \"Vampire Illusion\"",
    "49": "Scarlet Sign \"Scarlet Meister\"",
    "50": "\"Scarlet Gensokyo\"",
    "51": "Moon Sign \"Secret Dreamer of Scarlet\"",
    "52": "Sun Sign \"Royal Flare\"",
    "53": "Fire Water Wood Metal Earth Sign \"Philosopher's Stone\"",
    "54": "Taboo \"Cranberry Trap\"",
    "55": "Taboo \"Lævateinn\"",
    "56": "Taboo \"Four of a Kind\"",
    "57": "Taboo \"Kagome, Kagome\"",
    "58": "Taboo \"Maze of Love\"",
    "59": "Forbidden Barrage \"Starbow Break\"",
    "60": "Forbidden Barrage \"Catadioptric\"",
    "61": "Forbidden Barrage \"Clock that Ticks Away the Past\"",
    "62": "Jumping To Broken Dead Sister",
    "63": "F.L.A.N.D.R.E Forever Levels And Nether Dead Realm Ender"
}