{
    "0": "Horror \"Tsurube-Otoshi Apparition\"",
    "2": "Trap Sign \"Capture Web - Aimed -\"",
    "4": "Spider \"Cave Spider's Nest - Focused -\"",
    "6": "From The Start Sign \"Cobweb's Secret Art\"",
    "8": "From The Killer's Sign \"Cobweb's Secret Art\"",
    "10": "Jealousy Sign \"Green-Eyed Monster\"",
    "12": "Envy \"Green-Eyed Invisible Monster\"",
    "14": "Grandpa Hanasaka \"Jealousy of the Kind & Lovely\"",
    "16": "Grandpa Hanasaka \"Shiro's Ashes\"",
    "18": "Tongue-Cut Sparrow \"Hate for the Humble & Rich\"",
    "20": "Tongue-Cut Sparrow \"Large Box & Small Box\"",
    "22": "Malice Sign \"Shrine Visit in the Dead of Night\"",
    "24": "Malice Sign \"Day 7 of the Shrine Visits in the Dead of Night\"",
    "26": "Oni Sign \"Anomalies, Strength, Disorder, & Spirits\"",
    "30": "Mysterious Ring \"Hell's Wheel of Pain\"",
    "32": "Shackles Sign \"Shackles a Criminal Can't Take Off\"",
    "34": "Feat of Strength \"Storm on Mt. Ooe\"",
    "36": "Feat of Strength \"Wind Blowing Down from Mt. Ooe\"",
    "38": "Big Four Arcanum \"Knock Out In Three Steps\"",
    "40": "Big Four Arcanum \"Knock Out In Three Steps\"",
    "42": "Recollection \"Terrible Souvenir\"",
    "44": "Recollection \"Terrifying Hypnotism\"",
    "46": "Recollection \"Double Black Death Butterfly\"",
    "50": "Recollection \"Flying Insect's Nest\"",
    "54": "Recollection \"Border of Wave & Particle\"",
    "58": "Recollection \"Mt. Togakushi Toss\"",
    "62": "Recollection \"Night Parade of a Million Demons\"",
    "66": "Recollection \"Deep Fog Labyrinth\"",
    "70": "Recollection \"Wind God's Leaf-Veiling\"",
    "74": "Recollection \"Tengu's Macroburst\"",
    "78": "Recollection \"Torii Whorl-Wind\"",
    "82": "Recollection \"Spring Kyoto Dolls\"",
    "86": "Recollection \"Straw Doll Kamikaze\"",
    "90": "Recollection \"Return Inanimateness\"",
    "94": "Hidden Recollection Fire and Water sign \"Gyeser of Subterranean Floor\"",
    "98": "Combined Recollection \"Undine of Unying\"",
    "102": "A Perfect Recollection Of Terror \"5 Books of Scarlet Devil Mansion\"",
    "106": "Stolen Recollection \"Fire And The Flames Way\"",
    "110": "Stolen Recollection \"Red Face Lie of A Kappa?\"",
    "114": "Stolen Recollection \"Eternal Phantasmal Rose Garden\"",
    "118": "Cat Sign \"Cat's Walk\"",
    "120": "Cat Sign \"Vengeful Cat Spirit's Erratic Step\"",
    "122": "Cursed Sprite \"Zombie Fairy\"",
    "124": "Cursed Sprite \"Vengeful Spirit: Possessed Fairy\"",
    "126": "Malicious Spirit \"Spleen Eater\"",
    "128": "Corpse Spirit \"Vengeful Cannibal Spirit\"",
    "130": "Atonement \"Needle Mountain of a Former Hell\"",
    "132": "Atonement \"The Needles of Yore & the Vengeful Spirits in Pain\"",
    "134": "\"Rekindling of Dead Ashes\"",
    "136": "\"Small Demon's Revival\"",
    "138": "Youkai \"Blazing Wheel\"",
    "142": "Atomic Fire \"Nuclear Fusion\"",
    "144": "Atomic Fire \"Nuclear Excursion\"",
    "145": "Atomic Fire \"Uncontainable Nuclear Reaction\"",
    "146": "Explosion Sign \"Petit Flare\"",
    "147": "Explosion Sign \"Mega Flare\"",
    "148": "Explosion Sign \"Giga Flare\"",
    "149": "Explosion Sign \"Peta Flare\"",
    "150": "Blazing Star \"Fixed Star\"",
    "152": "Blazing Star \"Planetary Revolution\"",
    "153": "Blazing Star \"Ten Evil Stars\"",
    "154": "\"Hell & Heaven Meltdown\"",
    "156": "\"Hell's Tokamak\"",
    "158": "\"Hell's Artificial Sun\"",
    "160": "\"Subterranean Sun\"",
    "162": "Esoterica \"Nine Syllable Stabs\"",
    "163": "Miracle \"Miracle Fruit\"",
    "164": "Divine Virtue \"Bumper Crop Rice Shower\"",
    "165": "Image \"All Ancestors Standing Beside Your Bed\"",
    "166": "Image \"Danmaku Paranoia\"",
    "167": "Instinct \"Release of the Id\"",
    "168": "Suppression \"Super-Ego\"",
    "169": "Response \"Youkai Polygraph\"",
    "170": "Unconscious \"Rorschach in Danmaku\"",
    "171": "Rekindled \"The Embers of Love\"",
    "172": "Depths \"Genetics of the Unconscious\"",
    "173": "\"Philosophy of a Hated Person\"",
    "174": "\"Subterranean Rose\""
}