{
    "2": "Hammer Sign \"Pounding Hammer Ripples\"",
    "3": "Rabbit Sign \"Strawberry Massive Dango\"",
    "4": "Bullet Sign \"Rabbit Sneaker\"",
    "5": "Rabbit Sign \"Dango Rice Flower\"",
    "7": "Butterfly Sign \"Butterfly Scale Shreder\"",
    "8": "Summer Season Sign \"Bubbling Summer Time\"",
    "10": "Magic Sign \"Jizo's Curves of Steel\"",
    "11": "Magma to Lave Stomp",
    "12": "Four Golem Pets Rectangle",
    "14": "Wolf Sign \"Flag & Slash\"",
    "15": "Wolf Tengu's Sign \"Sword Trail Flare\"",
    "17": "Lucky 3 \"Chase Me & My Tails\"",
    "18": "Dog Sign \"Throw the Sticks Back\"",
    "21": "Dream Bullet \"Lunatic Dimensional Shots\"",
    "22": "Dango \"Dango Purifying Core\"",
    "23": "Dream Butterfly \"Butterfly Sane God\"",
    "24": "Dream Jizo \"Dreaming of Heaven and Hell\"",
    "25": "Dream Blade Exhaustion \"Fighting From Heaven and Hell\"",
    "26": "Dream Dog \"Jumping In the Puddling Rain\"",
    "28": "Hell Sign \"A-Maze Me Robot\"",
    "29": "Hell Sign \"Vally of Hell\"",
    "30": "Hell Flare Sign \"Eclipse Hell\"",
    "32": "Orb Sign \"Ghost-Wheels Of Fantasy Maidens\"",
    "33": "Orb Sign \"Good Thinking wouldn't Kill you\"",
    "34": "Dream Villian \"One-Winged Dream Villian\"",
    "36": "Foreign Sign \"Wendigo's Cut-lass Helix\"",
    "37": "Festival Sign \"Snakes Dancing Festival\"",
    "38": "Breaker Sign \"Blood Clot Breaker\"",
    "39": "Sheds From a Snake \"Reticulated Python\"",
    "41": "Otherworld \"Distorted Fire-Flower\"",
    "42": "Otherworld \"Resentful Rain of Hell\"",
    "43": "Moon \"Star Radiation\"",
    "44": "Triple Nightmare Goddess \"Moon, Heaven and Earth\"",
    "45": "\"Hells Collapse\"",
    "47": "\"Trembling, Shivering Nightmare\"",
    "48": "\"Removal Of Impurity\"",
    "49": "\"Rage Building Mother\"",
    "50": "\"Purely Distressing Danmaku\"",
    "51": "Light Eater \"Eating the Flowers of Light\"",
    "52": "Light Eater \"Light Ricey Ice\"",
    "53": "Baku Eater Sign \"Distressing Eater\"",
    "54": "Trapped Sign \"A Mimics Greatest trap\"",
    "55": "Baku's Depression \"Pulsing Heart\"",
    "57": "Scarlet Devil Sign \"Bloody Catastrophe\"",
    "61": "Divine Scarlet Sign \"Bloody Laser of Seventeen Articles\"",
    "62": "Scarlet Star Sign \"Superhuman Catastrophe Pilgrimage\"",
    "64": "Wind God Sign \"False Dreaming Onbashira Rain\"",
    "66": "Wind Flower Sign \"Hiding Behind the Law\"",
    "68": "Wind Flower Sign \"Trails by Faith\"",
    "72": "Pure Princess Sign \"Branch of Hourai's Spirits\"",
    "70": "Truer Sign \"Lunarian Rhapody!\"",
    "69": "Eternal Night Sign \"Bullet Branch of Hourai in a Pot\"",
    "74": "Lunar \"New World Order\"",
    "75": "Flare Spirit Sign \"Heart Stinger\"",
    "76": "Lost Sign \"Shikigami Faith of Fox's\"",
    "77": "\"Perfect Dance\"",
    "78": "Flare Mystic Sign \"Shikigami Touching Stars\"",
    "79": "Illusion God \"Descent of Iizuna-Gongen With Our Minds\"",
    "80": "Subterranean Sun Suppression",
    "81": "Hellish Combo Sign \"Simple Hell Dance\"",
    "82": "Dancing for the Blue Lady Sign \"Blue Lady & Scarlet Lady Show\"",
    "83": "Blue Lady Combo Sign \"Dance to the Beat\"",
    "84": "Lightning Sheep Sign \"Uncanny Posing\"",
    "85": "Posing with a Fish Sign \"Shocking Red Fish\"",
    "86": "Deep Blue Lady Sign \"Let's Sit Under the Song\"",
    "87": "Demons Sign \"Simple Starting\"",
    "88": "Double Pain \"Fire to Purity\"",
    "91": "Demon in Purist Hell Land",
    "92": "Stars Above Hell's Core",
    "93": "\"Secret God Barrier\"",
    "96": "\"Shoot the Danmaku Barrier!\"",
    "94": "\"Sneak-Photographer Exorcism Master Spark\"",
    "99": "\"The Nightmare One Has on Their Final Sunday\"",
    "100": "Paper Sign \"Zener Card Shuriken\"",
    "101": "Paper Sign \"Barrier-Enclosed Zener Card Shuriken\"",
    "58": "Star Divine Sign \"Superhuman of Seventeen Articles\"",
    "59": "Scarlet Star Sign \"Superhuman's Bloody Knife\"",
    "60": "Scarlet Divine Sign \"Catastrophe of Seventeen Articles\"",
    "63": "Mystic Flower Sign \"Butterfly Resurrection Storm Yama Scepter\"",
    "65": "Wind Mystic Sign \"Dead Butterfly Onbashira\"",
    "67": "Mystic Wind Sign \"Native Immortal Butterfly Storm\"",
    "71": "Eternal Moon Sign \"The Game of Life in The Illuminati\"",
    "73": "Purified Medicine \"Hourai Elixir\"",
    "79": "Earth Mystic Sign \"Shikigami of the Ego\"",
    "89": "Stars Above Hell's Core",
    "90": "A Demon Against Purified World",
    "95": "\"Sneak-Photographer Exorcism from the Back\"",
    "97": "\"Coward's Master Spark\"",
    "98": "\"Unauthorized Danmaku Photography is Strictly Prohibited\""
}
