{
    "2": "Hammer Sign \"Pounding Hammer Ripples\"",
    "3": "Rabbit Sign \"Strawberry Massive Dango\"",
    "4": "Bullet Sign \"Rabbit Sneaker\"",
    "5": "Rabbit Sign \"Dango Rice Flower\"",
    "7": "Butterfly Sign \"Butterfly Scale Shreder\"",
    "8": "Summer Season Sign \"Bubbling Summer Time\"",
    "10": "Magic Sign \"Jizo's Curves of Steel\"",
    "11": "Magma to Lave Stomp",
    "12": "Four Golem Pets Rectangle",
    "14": "Wolf Sign \"Flag & Slash\"",
    "15": "Wolf Tengu's Sign \"Sword Trail Flare\"",
    "17": "Lucky 3 \"Chase Me & My Tails\"",
    "18": "Dog Sign \"Throw the Sticks Back\"",
    "21": "Dream Bullet \"Lunatic Dimensional Shots\"",
    "22": "Dango \"Dango Purifying Core\"",
    "23": "Dream Butterfly \"Butterfly Sane God\"",
    "24": "Dream Jizo \"Dreaming of Heaven and Hell\"",
    "25": "Dream Blade Exhaustion \"Fighting From Heaven and Hell\"",
    "26": "Dream Dog \"Jumping In the Puddling Rain\"",
    "28": "Hell Sign \"A-Maze Me Robot\"",
    "29": "Hell Sign \"Vally of Hell\"",
    "30": "Hell Flare Sign \"Eclipse Hell\"",
    "32": "Orb Sign \"Ghost-Wheels Of Fantasy Maidens\"",
    "33": "Orb Sign \"Good Thinking wouldn't Kill you\"",
    "34": "Dream Villian \"One-Winged Dream Villian\"",
    "36": "Foreign Sign \"Wendigo's Cut-lass Helix\"",
    "37": "Festival Sign \"Snakes Dancing Festival\"",
    "38": "Breaker Sign \"Blood Clot Breaker\"",
    "39": "Sheds From a Snake \"Reticulated Python\"",
    "41": "Otherworld \"Distorted Fire-Flower\"",
    "42": "Otherworld \"Resentful Rain of Hell\"",
    "43": "Moon \"Star Radiation\"",
    "44": "Triple Nightmare Goddess \"Moon, Heaven and Earth\"",
    "45": "\"Hells Collapse\"",
    "47": "\"Trembling, Shivering Nightmare\"",
    "48": "\"Removal Of Impurity\"",
    "49": "\"Rage Building Mother\"",
    "50": "\"Purely Distressing Danmaku\"",
    "51": "Secret Ceremony \"Matarah Sukkha\"",
    "52": "Secret Ceremony \"The Rear Face's Wicked Flames\"",
    "53": "Back Sign \"Halo of the Absolute Secret God\"",
    "54": "Secret Ceremony \"Secret God's Behind-the-Scenes Danmaku\"",
    "55": "Secret Ceremony \"Arcane Dupion\"",
    "57": "Scarlet Devil Sign \"Bloody Catastrophe\"",
    "61": "Divine Scarlet Sign \"Bloody Laser of Seventeen Articles\"",
    "62": "Scarlet Star Sign \"Superhuman Catastrophe Pilgrimage\"",
    "64": "Wind God Sign \"Mishabashira\"",
    "66": "Wind Flower Sign \"Mishaguji-sama's Right and Wrong\"",
    "68": "Wind Flower Sign \"Onbashira Trial\"",
    "72": "Shining Night Sign \"Big Bullet Branch of Hourai\"",
    "70": "Scarlet Needle Sign \"Keystones Grow Bigger, Too!\"",
    "69": "Eternal Night Sign \"Bullet Branch of Hourai in a Pot\"",
    "74": "Scarlet Night Sign \"Bullet Keystones of Hourai\"",
    "75": "Earth Spirit Sign \"Mind Stellar Steal\"",
    "76": "Earth Mystic Sign \"Shikigami of the Id\"",
    "77": "\"Perfect Mind Control\"",
    "78": "Earth Mystic Sign \"Shikigami's Giant Star\"",
    "80": "Earth Spirit Sign \"Mind Stellar Relief\"",
    "81": "Divine Star Sign \"Unidentified Ghost-Light Crowd\"",
    "82": "Shining Heaven Sign \"Thunderclap Dondoko Drum\"",
    "83": "Shining Divine Sign \"Mysterious Dondoko Crowd\"",
    "84": "Scarlet Star Sign \"Unidentified Lightning Strike\"",
    "85": "Divine Scarlet Sign \"Stalker in a Thunderstorm\"",
    "86": "Shining Star Sign \"Unidentified Dondoko Drum\"",
    "87": "Gathering Night Sign \"Precious Life Scatters like Mist\"",
    "88": "Ultramarine Orb Sign \"Pure and Impure Danmaku\"",
    "91": "Gathering Orb Sign \"Mist Ray\"",
    "92": "Eternal Orb Sign \"An Unsullied Orb and a Much-Sullied Spirit\"",
    "93": "\"Secret God Barrier\"",
    "96": "\"Shoot the Danmaku Barrier!\"",
    "94": "\"Sneak-Photographer Exorcism Master Spark\"",
    "99": "\"The Nightmare One Has on Their Final Sunday\"",
    "100": "Paper Sign \"Zener Card Shuriken\"",
    "101": "Paper Sign \"Barrier-Enclosed Zener Card Shuriken\"",
    "58": "Star Divine Sign \"Superhuman of Seventeen Articles\"",
    "59": "Scarlet Star Sign \"Superhuman's Bloody Knife\"",
    "60": "Scarlet Divine Sign \"Catastrophe of Seventeen Articles\"",
    "63": "Mystic Flower Sign \"Butterfly Storm Yama Scepter\"",
    "65": "Wind Mystic Sign \"Dead Butterfly Onbashira\"",
    "67": "Mystic Wind Sign \"Native Butterfly Storm\"",
    "71": "Eternal Scarlet Sign \"Plummeting Bhava-agra in a Pot\"",
    "73": "Eternal Shining Sign \"Pot Growing Bigger\"",
    "79": "Earth Mystic Sign \"Shikigami of the Ego\"",
    "89": "Gathering Orb Sign \"Purely Beyond All in the Fog\"",
    "90": "Eternal Orb Sign \"Reckless Sacrifice's Reflection\"",
    "95": "\"Sneak-Photographer Exorcism from the Back\"",
    "97": "\"Coward's Master Spark\"",
    "98": "\"Unauthorized Danmaku Photography is Strictly Prohibited\""
}