{
    "0": "Assassin's Bullet \"Speed Strike\"",
    "2": "Bullet Sign \"Eagle Shooting\"",
    "5": "Bullet Sign \"The Eagle Has Shot Its Target\"",
    "6": "Gun Sign \"Lunatic Gun\"",
    "9": "Gun Sign \"Lunatic Gun\"",
    "10": "Harvest  Sign \"Tasting the Fruit\"",
    "12": "Harvest  Sign \"Tasting the Fruit\"",
    "14": "Harvest Taste Sign \"Bubbling Treasure\"",
    "18": "Star of Harvest \"Pull the Crops\"",
    "21": "Star of Harvest \"Crops of endless magnitude\"",
    "22": "Dream Sign \"Scarlet Nightmare\"",
    "24": "Dream Sign \"Scarlet Oppressive Nightmare\"",
    "26": "Dream Sign \"Indigo Dream of Anxiety\"",
    "28": "Dream Sign \"Indigo Three-Layered Dream of Anxiety\"",
    "29": "Dream Sign \"Eternally Anxious Dream\"",
    "30": "Dream Sign \"Ochre Confusion\"",
    "32": "Dream Sign \"Ochre Labyrinthine Confusion\"",
    "34": "Dream Sign \"Dream Catcher\"",
    "36": "Dream Sign \"Azure Dream Catcher\"",
    "37": "Dream Sign \"Losing Oneself in a Dream\"",
    "38": "Moon Sign \"Ultramarine Lunatic Dream\"",
    "42": "Orb Sign \"Disorderly Flock's Curse\"",
    "44": "Orb Sign \"Disorderly Flock's Reverse Curse\"",
    "46": "Orb Sign \"Impure Body Detection Mines\"",
    "48": "Orb Sign \"Impure Body Detection Mines V2\"",
    "50": "Orb Sign \"Shotgun Coronation of the Gods\"",
    "52": "Orb Sign \"Shining Shotgun Coronation of the Gods\"",
    "54": "\"One-Winged White Heron\"",
    "58": "Hell Sign \"Hell Eclipse\"",
    "60": "Hell Sign \"Eclipse of Hell\"",
    "62": "Hell Sign \"Flash and Stripe\"",
    "64": "Hell Sign \"Star and Stripe\"",
    "66": "Hellfire \"Graze Inferno\"",
    "69": "Hellfire \"Infernal Essence of Grazing\"",
    "70": "Inferno \"Striped Abyss\"",
    "74": "\"Fake Apollo\"",
    "76": "\"Apollo Hoax Theory\"",
    "78": "\"Pure Light of the Palm\"",
    "82": "\"Murderous Lilies\"",
    "86": "\"Primordial Divine Spirit World\"",
    "88": "\"Modern Divine Spirit World\"",
    "90": "\"Trembling, Shivering Star\"",
    "94": "\"Pristine Lunacy\"",
    "98": "\"Overflowing Blemishes\"",
    "101": "\"Refinement of Earthen Impurity\"",
    "102": "Pure Sign \"Purely Bullet Hell\"",
    "104": "Pure Sign \"A Pristine Danmaku Hell\"",
    "106": "Trauma \"Spining on a lava bench\"",
    "107": "Paranoia \"Anxiety breakdown of a Human\"",
    "108": "??? \"The Door towards the Kingdom of Hearts and Hartless\"",
    "109": "Sustained Mugenri's Shrine Maiden \"The Glims Inside of the Mind\"",
    "110": "Underfire \"Cards Against Humanity\"",
    "111": "Zellus Dance \"Bounce Back towards Dance Back\"",
    "112": "\"Simple Danmaku for Cornering a Trapped Rat\"",
    "113": "In a Barrier of Mugenri \"Danmaku Danmaku\"",
    "114": "Monochrome Ray Fake \"No Eyedea\"",
    "115": "The Moon Copy sign \"Mugenri Impact\"",
    "116": "\"The Yellow walls of a Twin Card\"",
    "117": "\"Shall we dance once\"",
    "118": "\"Shall we dance For the Eternal Dance Engine?~\"",
    "45": "Orb Sign \"Disorderly Flock's Duplex Curse\""
}